// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpRz1zXh1QDvf2qOb2gdqfmNocHORkI8o',
    appId: '1:641320616883:web:0435ef1493efec4a7181c6',
    messagingSenderId: '641320616883',
    projectId: 'app-prueba-ff7f0',
    authDomain: 'app-prueba-ff7f0.firebaseapp.com',
    databaseURL: 'https://app-prueba-ff7f0-default-rtdb.firebaseio.com',
    storageBucket: 'app-prueba-ff7f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5Cmdh2SbUxs7n3v9-cgl9TqjiXcf-rk',
    appId: '1:641320616883:android:f81c9c5b180aeca07181c6',
    messagingSenderId: '641320616883',
    projectId: 'app-prueba-ff7f0',
    databaseURL: 'https://app-prueba-ff7f0-default-rtdb.firebaseio.com',
    storageBucket: 'app-prueba-ff7f0.firebasestorage.app',
  );

}